Add missing option when linking the hello-world program using the C standard library
Needed to specify the OS version, otherwise got the error:
`ld: symbol dyld_stub_binding_helper not found, normally in crt1.o/dylib1.o/bundle1.o for inferred architecture x86_64`
Found by doing `gcc hello-world-lib.o -o hello-world-lib -lc -v` and experimenting with the output flags that GCC was using.